"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar, NavbarBrand, NavbarContent, NavbarItem, Link, Button } from "@nextui-org/react";
import {Providers} from "./providers";

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <head>
        <title>Tray App</title>
        <meta name='description' content='Generated by Tray' />
      </head>
      <body className={inter.className}>
          <Providers>
          <Navbar>
            <NavbarBrand>
              <Link color="foreground" href="/dashboard" >
                <p className="font-bold text-inherit">TRAY</p>
              </Link>
            </NavbarBrand>
            <NavbarContent className="hidden sm:flex gap-4" justify="center">
              <NavbarItem>
                <Link color="foreground" href="/vendedor">
                  Vendedores
                </Link>
              </NavbarItem>
              <NavbarItem>
                <Link color="foreground" href="/venda" >
                  Vendas
                </Link>
              </NavbarItem>
              <NavbarItem>
                <Link color="foreground" href="/email">
                  Email
                </Link>
              </NavbarItem>
            </NavbarContent>
            <NavbarContent justify="end">
              <NavbarItem className="hidden lg:flex">
                <Link color="foreground" href="/login">Login</Link>
              </NavbarItem>
            </NavbarContent>
          </Navbar>
          {children}
        </Providers>
      </body>
    </html>
  )
}
